### PR TITLE
Make use of updated lunarity lexer

### LINKED ISSUE #547: Latest Rust version compiles main branch went error
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: 3.3.0-rc.8
- **Operating system**: Linux ARM64
- **Installation**: built from source

When compile main branch with latest Rust version 1.55.0 on ARM Linux, one package occurs error: `logos-derive`, and it shows error like:
```
$ cargo +nightly check
   Compiling logos-derive v0.7.7
error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> /home/birchmd/.cargo/registry/src/github.com-1ecc6299db9ec823/logos-derive-0.7.7/src/lib.rs:55:20
    |
55  |             extras.insert(util::ident(&ext), |_| panic!("Only one #[extras] attribute can be declared."));
    |                    ^^^^^^ -----------------  ----------------------------------------------------------- supplied 2 arguments
    |                    |
    |                    expected 1 argument
    |
note: associated function defined here

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> /home/birchmd/.cargo/registry/src/github.com-1ecc6299db9ec823/logos-derive-0.7.7/src/lib.rs:89:23
    |
89  |                 error.insert(variant, |_| panic!("Only one #[error] variant can be declared."));
    |                       ^^^^^^ -------  -------------------------------------------------------- supplied 2 arguments
    |                       |
    |                       expected 1 argument
    |
note: associated function defined here

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> /home/birchmd/.cargo/registry/src/github.com-1ecc6299db9ec823/logos-derive-0.7.7/src/lib.rs:93:21
    |
93  |                 end.insert(variant, |_| panic!("Only one #[end] variant can be declared."));
    |                     ^^^^^^ -------  ------------------------------------------------------ supplied 2 arguments
    |                     |
    |                     expected 1 argument
    |
note: associated function defined here

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0061`.
error: could not compile `logos-derive`

To learn more, run the command again with --verbose.
```

That's how far I could get.

### PR DESCRIPTION
**Pull request by rimrakhimov**
Closes #547

Updated 'lunarity-lexer' version is used that allows the client to compile with rust versions >=1.53.0

### CODE REVIEW

**Comment by 717a56e1** [comment]
#463 fixes this as well, completely gets rid of lunarity-lexer. Been waiting on a merge for months.

**Comment by varasev** [comment]
@rimrakhimov Can we close this in favor of the merged https://github.com/openethereum/openethereum/pull/463?

**Comment by rimrakhimov** [comment]
@varasev Yes
